name: 'echo'
description: 'write arguments to the standard output'
inputs:
  s:  # id of input
    description: '[string]'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.s }}
